# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6735745be5cd6ef241661aef522bb4a72981bfaaee37e816ef568f15644ddc220c5ec961bb41428bded3c72ac3b579e5486499ef6208a4ba787011b61d106274

test:
  secret_key_base: 25fb9890c22755e0a55d214b33a225de8d548666b1cd474bc628e43273f0ef0ecb9e8c48a38e55e92e9e77d6ed13277d0323f15397c048998587af3ce21e4a09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
